### ISSUE TITLE
TLS Termination

### ISSUE THREAD

**Issue by lowellmower** [lowellmower/homeBotty#2]
The internal proxy must conduct TLS termination of a request from the public internet and succesfully forward the request to the device router on the internal network.

#### TODO:
- [ ] Integrate with [Let's Encrypt!](https://letsencrypt.org/)
- [ ] Allow the request to continue on to the `LAN` unencrypted
- [ ] At minimum, a document detailing key rotation
- [ ] Tooling where necessary around maintenance, e.g. rolling keys
