### ISSUE TITLE
Design and Document Metric Collections Solution

### ISSUE THREAD

**Issue by lowellmower** [lowellmower/homeBotty#5]
Write up and design a small metrics collection solution which does not add overhead to the project as a whole. This solution should include an interface for monitoring and a simple collection strategy which is modular enough to apply to all parts of the system.

As a first go of things, toy with an MVP which can easily be torn down and replaced. Create any feature tickets necessary for follow up work.

#### TODO
- [ ] Decide on the software to be used in metrics collection
- [ ] Flesh out basic design and document useage
- [ ] Apply collected knowledge to an MVP
- [ ] Document snags, gotchas, and necessary set up commands
- [ ] Create follow up issues for final implementation
