### ISSUE TITLE
Design and Document HoBot

### ISSUE THREAD

**Issue by lowellmower** [lowellmower/homeBotty#7]
A rough design and system integration document needs to be sketched for the slack bot integration. No MVP is required but toying with software is encouraged as part of this step. Main outcomes should be around the following:
- Useage
- Integration
- Communication
- Modularity 
- Distribution
- Artificial Learning

#### TODO
- [ ] Write a problem statement
- [ ] Discuss solutions to the problem statement including non technical
- [ ] Draft HoBot proposal and include feature ideas
- [ ] Document software and tool usage as well as any technical steps during toying
