### ISSUE TITLE
Terms and Conditions of "Out of Box" Solutions

### ISSUE THREAD

**Issue by lowellmower** [lowellmower/homeBotty#8]
A crux of the problem statement is the assumption that data collection and profitability from said collection is a by product of using out of the box solutions like Sonoff, Nest, etc. Atop that, another assumption is that vast swathes of data which users may not want another human to have access to may not explicitly be protected under a form legal agreement. These assumptions should be more thoroughly researched and detailed by an analysis of various terms and conditions statements as well as some light poking and prodding.

Questions to think about:
- What data is collected?
- How is that data stored? Can we even find out?
- Is that data shared? If so, with whom and for what purpose?
- Can a user request their data?
- Can a user request their data be deleted?
- What correlations exist between a solution and its competitors?
- What are some differences?
- What did you find which was surprising in a positive way?
- What did you find which was surprising in a negative way?
- How can things be different for the better?

#### TODO:
- [x] Create assessment matrix
- [ ] Read [Nest's terms and conditions](https://nest.com/legal/terms-of-service/)
- [ ] Read [Ecobees terms and conditions](https://www.ecobee.com/legal/)
- [ ] Read [Xfinity Home terms and conditions](https://www.xfinity.com/cdn.comcast.com/~/Media/Files/Legal/XH/Control-updated.pdf?vs=1)
- [ ] Read [Amazon Echo terms and conditions](https://www.amazon.com/gp/help/customer/display.html?nodeId=201809740)
- [ ] Read [Sonoff terms and conditions](https://www.itead.cc/privacy_and_notice)
- [ ] Read [Google dot terms and conditions](https://support.google.com/googlehome/answer/7072285?hl=en)
- [ ] Read [ISP terms and conditions](http://wifilogin.xfinity.com/wifiagreement.php) and [Privacy Statement](https://my.xfinity.com/privacy/)
- [ ] Detail findings and draw conclusions
